# Default configuration for mips64-softmmu

include mips-softmmu-common.mak
CONFIG_RC4030=y
CONFIG_DP8393X=y
CONFIG_DS1225Y=y
CONFIG_JAZZ=y
CONFIG_G364FB=y
CONFIG_JAZZ_LED=y
CONFIG_DDC=y
CONFIG_DS1338=y
CONFIG_DUNA=y
CONFIG_SSI=y
CONFIG_SSI_M25P80=y
