/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "trace.h"

uint16_t _TRACE_EBUS_ISA_IRQ_HANDLER_DSTATE;
uint16_t _TRACE_SUN4U_IOMMU_MEM_READ_DSTATE;
uint16_t _TRACE_SUN4U_IOMMU_MEM_WRITE_DSTATE;
uint16_t _TRACE_SUN4U_IOMMU_TRANSLATE_DSTATE;
TraceEvent _TRACE_EBUS_ISA_IRQ_HANDLER_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "ebus_isa_irq_handler",
    .sstate = TRACE_EBUS_ISA_IRQ_HANDLER_ENABLED,
    .dstate = &_TRACE_EBUS_ISA_IRQ_HANDLER_DSTATE 
};
TraceEvent _TRACE_SUN4U_IOMMU_MEM_READ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sun4u_iommu_mem_read",
    .sstate = TRACE_SUN4U_IOMMU_MEM_READ_ENABLED,
    .dstate = &_TRACE_SUN4U_IOMMU_MEM_READ_DSTATE 
};
TraceEvent _TRACE_SUN4U_IOMMU_MEM_WRITE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sun4u_iommu_mem_write",
    .sstate = TRACE_SUN4U_IOMMU_MEM_WRITE_ENABLED,
    .dstate = &_TRACE_SUN4U_IOMMU_MEM_WRITE_DSTATE 
};
TraceEvent _TRACE_SUN4U_IOMMU_TRANSLATE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sun4u_iommu_translate",
    .sstate = TRACE_SUN4U_IOMMU_TRANSLATE_ENABLED,
    .dstate = &_TRACE_SUN4U_IOMMU_TRANSLATE_DSTATE 
};
TraceEvent *hw_sparc64_trace_events[] = {
    &_TRACE_EBUS_ISA_IRQ_HANDLER_EVENT,
    &_TRACE_SUN4U_IOMMU_MEM_READ_EVENT,
    &_TRACE_SUN4U_IOMMU_MEM_WRITE_EVENT,
    &_TRACE_SUN4U_IOMMU_TRANSLATE_EVENT,
  NULL,
};

static void trace_hw_sparc64_register_events(void)
{
    trace_event_register_group(hw_sparc64_trace_events);
}
trace_init(trace_hw_sparc64_register_events)
