# CAN bus interfaces emulation and infrastructure

obj-$(CONFIG_DUNA) += sc64-can.o

common-obj-y += can_core.o
ifeq ($(CONFIG_LINUX),y)
common-obj-y += can_socketcan.o
else
common-obj-y += can_host_stub.o
endif
